% covers: 17 - reshape(A, sz), one [] placeholder in reshape, and repmat(A, sz)
disp(reshape(1:6, [3 2]))
disp(size(reshape(1:6, [], 2)))
disp(size(reshape(1:6, 2, [])))
disp(repmat([1 2], [2 2]))
disp(size(repmat(1, [2 3])))
disp(reshape(1:6, [], 3))
disp(size(reshape(1:6, [], 1)))
disp(size(reshape(zeros(0, 3), [], 2)))
disp(reshape([1 2; 3 4; 5 6], 2, []))
disp(repmat([1; 2], [1 3]))
disp(size(repmat([1 2], [2])))
