% covers: 12 - a continuation straight after a digit lexes, and the forms that already work stay working
a = 1...
+ 2; disp(a)
b = 1 ...
+ 2; disp(b)
x = 5;
c = x...
+ 1; disp(c)
d = (1)...
+ 2; disp(d)
e = [1 2]...
+ 1; disp(e)
f = 1.0...
+ 2; disp(f)
