% covers: Scope, exist feval - a run of 'feval' names reaching the builtin is one call, so a
% chain inside deep recursion is neither a stack overflow nor quadratic. Before cycle 05's
% review fix this exact script, 499 frames each running a 300-long chain, overflowed the
% stack (0xC00000FD on Windows, 134 on Linux); checked against the pre-fix build
r = f(1);
disp(r)
function r = f(n)
if n >= 499, r = n; return; end
r = feval('feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'feval', 'f', n + 1);
end
